### ISSUE TITLE
query string params not attached to params  variable

### ISSUE THREAD

**Issue by jon49** [benallfree/pocketpages#21]
I'm using the @next version with pocketbase 23.5. When I do the minimal start with @next pocketpages I changed the index.ejs file to be:

```html
<p>Hello, <%= params.msg %></p>
 ```

And the message in the URL http://127.0.0.1:8090/?msg=Pocketpages

Doesn't show on the page. Logging what params is by doing this:

```html
<%
console.log(stringify(params));
%>
```

Shows the `params` to be `{}`.

**Comment by benallfree** [comment]
Please go back to @latest, I need to pull @next.
