### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by cdes** [benallfree/pocketpages#6]
Brilliant work! However, I was browsing the docs for pocketpages, and notices a 2-3 seconds loading time for pages which is painfully slow.

Here's a screen recording of the issue:
![CleanShot 2024-09-27 at 12 47 47](https://github.com/user-attachments/assets/caad8090-3e56-4592-9c4b-b4c3a49b2057)

To compare, here's me browsing pocketbase docs:
![CleanShot 2024-09-27 at 12 49 55](https://github.com/user-attachments/assets/f79c938f-85c4-4031-b7eb-95b6afbcc14b)

Hope this helps!

**Comment by benallfree** [comment]
This has been fixed in v0.8.2 :)
