### ISSUE TITLE
"could not determine executable to run"

### ISSUE THREAD

**Issue by ndarilek** [benallfree/pocketpages#8]
Hello, I'm trying to get started with pocketpages and get the following error:

```bash
nolan@nolan-framework:~/Projects$ npx pocketpages new names-are-hard                                               
npm ERR! could not determine executable to run                                                                     
                                                                                                                   
npm ERR! A complete log of this run can be found in: /home/nolan/.npm/_logs/2024-10-25T20_51_11_224Z-debug-0.log   
```

Seeing similar with `bunx` too.

Logs don't appear super helpful, though they do include all relevant versions so I'll include them here.

```
0 verbose cli /home/nolan/.asdf/installs/nodejs/20.7.0/bin/node /home/nolan/.asdf/installs/nodejs/20.7.0/lib/node_modules/npm/bin/npm-cli.js                                                                                          
1 info using npm@10.1.0                                                                                            
2 info using node@v20.7.0                                                                                          
3 timing npm:load:whichnode Completed in 1ms                                                                       
4 timing config:load:defaults Completed in 2ms                                                                     
5 timing config:load:file:/home/nolan/.asdf/installs/nodejs/20.7.0/lib/node_modules/npm/npmrc Completed in 0ms     
6 timing config:load:builtin Completed in 0ms                                                                      
7 timing config:load:cli Completed in 2ms                                                                          
8 timing config:load:env Completed in 0ms                                                                          
9 timing config:load:file:/home/nolan/Projects/.npmrc Completed in 0ms                                             
10 timing config:load:project Completed in 4ms                                                                     
11 timing config:load:file:/home/nolan/.npmrc Completed in 0ms                                                     
12 timing config:load:user Completed in 0ms                                                                        
13 timing config:load:file:/home/nolan/.asdf/installs/nodejs/20.7.0/etc/npmrc Completed in 0ms                     
14 timing config:load:global Completed in 0ms                                                                      
15 timing config:load:setEnvs Completed in 1ms                                                                     
16 timing config:load Completed in 9ms                                                                             
17 timing npm:load:configload Completed in 9ms                                                                     
18 timing config:load:flatten Completed in 1ms                                                                     
19 timing npm:load:mkdirpcache Completed in 0ms                                                                    
20 timing npm:load:mkdirplogs Completed in 1ms                                                                     
21 verbose title npm exec pocketpages new names-are-hard                                                           
22 verbose argv "exec" "--" "pocketpages" "new" "names-are-hard"                                                   
23 timing npm:load:setTitle Completed in 0ms                                                                       
24 timing npm:load:display Completed in 1ms                                                                        
25 verbose logfile logs-max:10 dir:/home/nolan/.npm/_logs/2024-10-25T20_51_11_224Z-                                
26 verbose logfile /home/nolan/.npm/_logs/2024-10-25T20_51_11_224Z-debug-0.log                                     
27 timing npm:load:logFile Completed in 5ms                                                                        
28 timing npm:load:timers Completed in 0ms                                                                         
29 timing npm:load:configScope Completed in 0ms                                                                    
30 timing npm:load Completed in 29ms                                                                               
31 timing arborist:ctor Completed in 1ms                                                                           
32 silly logfile done cleaning log files                                                                           
33 http fetch GET 200 https://registry.npmjs.org/pocketpages 209ms (cache miss)                                    
34 timing command:exec Completed in 228ms                                                                          
35 verbose stack Error: could not determine executable to run                                                      
35 verbose stack     at getBinFromManifest (/home/nolan/.asdf/installs/nodejs/20.7.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)                                                                 
35 verbose stack     at exec (/home/nolan/.asdf/installs/nodejs/20.7.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:188:15)                                                                                              
35 verbose stack     at async module.exports (/home/nolan/.asdf/installs/nodejs/20.7.0/lib/node_modules/npm/lib/cli-entry.js:61:5)                                                                                                    
36 verbose pkgid pocketpages@0.8.0                                                                                 
37 verbose cwd /home/nolan/Projects                                                                                
38 verbose Linux 5.15.153.1-microsoft-standard-WSL2                                                                
39 verbose node v20.7.0                                                                                            
40 verbose npm  v10.1.0                                                                                            
41 error could not determine executable to run                                                                     
42 verbose exit 1                                                                                                  
43 timing npm Completed in 488ms                                                                                   
44 verbose code 1                                                                                                  
45 error A complete log of this run can be found in: /home/nolan/.npm/_logs/2024-10-25T20_51_11_224Z-debug-0.log   
```

Thanks.

**Comment by esencys** [comment]
Hi @ndarilek thank you for posting this. I ran into the same error, unable to find the executable to run. 

I downgraded the pocketpages version to 0.2.0 and that's got an executable. However the node module had a different file structure and was missing a file.

Also, really cool project @benallfree! Thanks for your work in the pocketbase and Go open-source communities. Blessed to be able to have platforms like PocketHost. 

`❯ npm run dev

> dev
> pocketpages serve --hooksDir=app --dev

node:fs:3034
  binding.copyFile(
          ^

Error: ENOENT: no such file or directory, copyfile '/Users/yshen/repos/pocketpages-explorations/node_modules/pocketpages/lib/+boot.pb.js' -> 'app/+pocketpages.pb.js'
    at copyFileSync (node:fs:3034:11)
    at ensureBootloader (/Users/yshen/repos/pocketpages-explorations/node_modules/pocketpages/cli/util/ensureBootloader.ts:8:3)
    at Command.<anonymous> (/Users/yshen/repos/pocketpages-explorations/node_modules/pocketpages/cli/ServeCommand.ts:30:13)
    at Command.listener [as _actionHandler] (/Users/yshen/repos/pocketpages-explorations/node_modules/commander/lib/command.js:542:17)
    at /Users/yshen/repos/pocketpages-explorations/node_modules/commander/lib/command.js:1502:14
    at Command._chainOrCall (/Users/yshen/repos/pocketpages-explorations/node_modules/commander/lib/command.js:1386:12)
    at Command._parseCommand (/Users/yshen/repos/pocketpages-explorations/node_modules/commander/lib/command.js:1501:27)
    at /Users/yshen/repos/pocketpages-explorations/node_modules/commander/lib/command.js:1265:27
    at Command._chainOrCall (/Users/yshen/repos/pocketpages-explorations/node_modules/commander/lib/command.js:1386:12)
    at Command._dispatchSubcommand (/Users/yshen/repos/pocketpages-explorations/node_modules/commander/lib/command.js:1261:25) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/Users/yshen/repos/pocketpages-explorations/node_modules/pocketpages/lib/+boot.pb.js',
  dest: 'app/+pocketpages.pb.js'
}

Node.js v20.18.0`

**Comment by benallfree** [comment]
@ndarilek @esencys I've updated the docs at https://pocketpages.dev.

Can you please try:

```
npm i pocketpages@latest
cp -r node_modules/pocketpages/starters/minimal/pb_hooks pb_hooks
pocketbase --dir=pb_data --dev serve
open http://localhost:8090
```

**Comment by esencys** [comment]
> @ndarilek @esencys I've updated the docs at https://pocketpages.dev.
> 
> Can you please try:
> 
> ```
> npm i pocketpages@latest
> cp -r node_modules/pocketpages/starters/minimal/pb_hooks pb_hooks
> pocketbase --dir=pb_data --dev serve
> open http://localhost:8090
> ```

Hi @benallfree. Thank you so much for the quick response! With the existing setup, I've ran the following serve command with a similar error when using the `pocketbase` package.
![Screenshot 2024-10-27 at 5 23 36 PM](https://github.com/user-attachments/assets/e5f85f4b-86d0-48c8-9e5a-e18e32bff82d)


Instead of an npm package, I installed pocketbase directly via homebrew and that's **successful**. Thank you!
![Screenshot 2024-10-27 at 5 46 49 PM](https://github.com/user-attachments/assets/3b0a24c8-b0e1-4934-b335-e257c806e1b5)



On a side note, my earlier attempt had a `package.json` that started from the `npm init` command and I've ran the command to install pocketpages. 
![Screenshot 2024-10-27 at 5 54 14 PM](https://github.com/user-attachments/assets/d289716b-1a71-4fbb-a921-b866452f5f73)
However, I attempted to test your suggestions from a folder starting from the minimal starter folder but was not able to install the node modules via `npm i` nor `bun i`. The following results were shown on the console but seems like it might be more of a bun and mac issue and not pocketpages.
![Screenshot 2024-10-27 at 5 56 38 PM](https://github.com/user-attachments/assets/1528c49f-f4d9-4591-b4a5-b95f66a6a895)

**Comment by benallfree** [comment]
@esencys I'm sorry, I forgot to update the starter kits. Fixed in v0.8.2. Please try again.

**Comment by esencys** [comment]
That's alright. Thank you so much! Confirming that running the README instructions from latest pocketpages starter (v0.8.2) works as expected.

**Comment by benallfree** [comment]
Perfect, let's close this one since it seems to be working on the latest versions.

**Comment by ndarilek** [comment]
Finally had time to play with this and wanted to confirm that it now works. Thanks, this is a great project!
