### ISSUE TITLE
Slot variables undefined error when using layouts

### ISSUE THREAD

**Issue by esencys** [benallfree/pocketpages#9]
Hi @benallfree , thanks again for your work with Pocketpages. I was exploring the docs and ran into an issue when using multiple slots in my `+layout.ejs` file where the variables are not found.  
![Screenshot 2024-10-27 at 6 42 46 PM](https://github.com/user-attachments/assets/c8ceed71-19b3-4cb8-a95c-cb5a70515b36)
![Screenshot 2024-10-27 at 6 46 41 PM](https://github.com/user-attachments/assets/c758b4bc-4972-4fcd-bf71-669f5069acf1)

Also confirming that the slots work when using a single slot via `<%- slot ->`, as seen in the `daisyui` template.

Thank you.

**Comment by benallfree** [comment]
Updated in v0.9.0 just now. https://pocketpages.dev/docs/layouts

**Comment by esencys** [comment]
Confirmed that the slot variables can be used in v0.9.0. Thanks for the quick updates! Awesome work. 😸
